Repository techlottus/portalverse, pull requests merged in 2023-10, with the labels that each got.

#326 [ENG-1216] delete and test favicon multitenant
  public/favicon.ico
  utils/fetch-multitenant.js
Labels: enhancement

#327 Develop
  public/favicon.ico
  utils/fetch-multitenant.js
Labels: enhancement

#328 [ENG-1220]
  components/StaticProgramContent.tsx
Labels: bug

#329 Develop
  components/StaticProgramContent.tsx
Labels: bug

#331 [ENG-1233] change news section titles by brand on the internationalization page
  pages/nosotros/internacionalizacion.tsx
Labels: bug, enhancement

#332 [ENG-1243] Add scroll y on modal component
  old-components/Modal/Modal.tsx
Labels: bug, enhancement

#336 [ENG-753] Campus detail programs component
  components/sections/ProgramAccordionList.tsx
  utils/Renderers.tsx
  utils/getFilteredPrograms.ts
  utils/getPageDataById.ts
  utils/strapi/queries.ts
  utils/strapi/sections/ProgramAccordionItems.ts
Labels: enhancement

#337 Merge develop into main
  components/sections/ProgramAccordionList.tsx
  utils/Renderers.tsx
  utils/getFilteredPrograms.ts
  utils/getPageDataById.ts
  utils/strapi/queries.ts
  utils/strapi/sections/ProgramAccordionItems.ts
Labels: enhancement

#335 [ENG-1236] Generate component renderer
  components/sections/RockstarInfo.tsx
  components/sections/RockstarInfoList.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/RockstarInfloList.ts
Labels: enhancement

#338 Develop
  components/sections/RockstarInfo.tsx
  components/sections/RockstarInfoList.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/RockstarInfloList.ts
Labels: enhancement

#339 [ENG-1300] Fix UANE/UTEG form bug
  utils/getEducativeOffer.ts
Labels: bug

#341 feat: add title section
  pages/nosotros/empleabilidad.tsx
Labels: enhancement

#342 [ENG-1307] fetch to add redirects to configuration
  .gitignore
  next.config.js
  package.json
  utils/fetchRedirectsData.js
  utils/getRedirectsData.js
Labels: enhancement

#343 Develop
  .gitignore
  next.config.js
  package.json
  pages/nosotros/empleabilidad.tsx
  utils/fetchRedirectsData.js
  utils/getRedirectsData.js
Labels: enhancement

#344 [ENG-1311] Add title to Google Maps Section <Renderer>
  components/sections/GoogleMap.tsx
  utils/strapi/sections/GoogleMap.ts
Labels: enhancement

#345 [ENG-1333]Update rockstars info component & page
  components/sections/RockstarInfo.tsx
  components/sections/RockstarInfoList.tsx
  old-components/PaginatorPortalverse.tsx
Labels: enhancement

#346 Merge develop into main
  components/sections/GoogleMap.tsx
  components/sections/RockstarInfo.tsx
  components/sections/RockstarInfoList.tsx
  old-components/PaginatorPortalverse.tsx
  utils/strapi/sections/GoogleMap.ts
Labels: enhancement

#347 [ENG-1314] add title and description to SliderPortalverseWraper section
  components/sections/HeroSlider.tsx
  utils/strapi/sections/HeroSlider.ts
Labels: enhancement

#348 [ENG-1316] create renderer, section and query to mosaic section
  components/sections/MosaicSection.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/Mosaic.ts
Labels: enhancement

#351 [ENG-1367] remove minimum number of items on mobile for rockstarsList
  components/sections/RockstarInfoList.tsx
Labels: bug, enhancement

#352 Develop
  components/sections/HeroSlider.tsx
  components/sections/MosaicSection.tsx
  components/sections/RockstarInfoList.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/HeroSlider.ts
  utils/strapi/sections/Mosaic.ts
Labels: enhancement

#349 [ENG-1361] add renderer to BannerNumeralia section
  components/sections/BannerNumeraliaSection.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/BannerNumeralia.ts
Labels: enhancement

#350 [ENG-1364] The renderer of the section for repeatable banner was generated
  components/sections/RepeatableBannerSection.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/RepeatableBanner.ts
Labels: enhancement

#353 [ENG-1399] generation of the renderer for the Videos section
  components/sections/VideosSection.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/Videos.ts
Labels: enhancement

#354 [ENG-1406] generation of the renderer for the image section with introduction
  components/sections/IntroductionImage.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/IntroductionImage.ts
Labels: enhancement

#356 Develop
  components/sections/BannerNumeraliaSection.tsx
  components/sections/CardsStatistics.tsx
  components/sections/IntroductionImage.tsx
  components/sections/RepeatableBannerSection.tsx
  components/sections/VideosSection.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/BannerNumeralia.ts
  utils/strapi/sections/CardList.ts
  utils/strapi/sections/CardsStatistics.ts
  utils/strapi/sections/IntroductionImage.ts
  utils/strapi/sections/RepeatableBanner.ts
  utils/strapi/sections/Videos.ts
Labels: enhancement
