Repository techlottus/portalverse, pull requests merged in 2024-08, with the labels that each got.

#907 [ADQ-307] fix meta viewport
  components/BlogEntryPageContent.tsx
  components/PageContent.tsx
  components/ProgramBachilleratoPageContent.tsx
  components/ProgramSuperiorPageContent.tsx
  components/sections/ContEdProgramDetail.tsx
  pages/admisiones/index.tsx
  pages/egresados/index.tsx
  pages/index.tsx
  pages/nosotros/campus.tsx
  pages/nosotros/internacionalizacion.tsx
Labels: bug

#915 [ADQ-286] create ImageVideo section
  components/sections/VideoImage.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/VideoImageSection.ts
Labels: Feature

#899 [ADQ-285] Added query and renders for tabs organism
  components/sections/TabList.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/TabList.ts
Labels: enhancement, Feature
