Repository techlottus/portalverse, pull requests merged in 2024-07, with the labels that each got.

#743 [LOT-990] Formulario UVT
  forms/container/ScheduleVisitForm.tsx
Labels: enhancement

#746 feat: added redirection to cards
  old-components/IntroducctionProgram.tsx
Labels: bug

#747 Develop
  forms/container/ScheduleVisitForm.tsx
  old-components/IntroducctionProgram.tsx
Labels: bug

#751 [ADQ-162] Solution to the issue where filters on mobile overlap
  old-components/FilterDropdown/FilterDropdown.tsx
Labels: bug

#754 [LOT-1008] Checkout flywire iframe mobile
  pages/_app.tsx
  pages/checkout/[program]/[id].tsx
Labels: bug

#766 [FEAT/LOT-1037] fix: added initial filtering on campus filter
  components/ProgramSuperiorPageContent.tsx
  components/sections/ProgramsFilter.tsx
Labels: bug

#823 [ADQ-239] Add robots fetch
  next-sitemap.config.js
  utils/fetchGeneralData.js
  utils/getGeneralData.js
Labels: enhancement

#861 [ADQ-218] Homologar Espaciados entre componentes dinámicos | Páginas dinámicas
  components/sections/ListconfigBlogPosts.tsx
  components/sections/ListconfigVacancies.tsx
Labels: Feature

#862 [ADQ-219] Homologar Espaciados entre componentes dinámicos | Páginas dinámicas
  components/sections/BlogPostsPodcast.tsx
  components/sections/OutstandingList.tsx
Labels: Feature

#863 [ADQ-220] Homologar Espaciados entre componentes dinámicos | Páginas dinámicas
  components/ProgramSuperiorPageContent.tsx
  components/sections/RockstarInfoList.tsx
  pages/nosotros/empleabilidad.tsx
Labels: Feature

#889 [ADQ-279] Build GraduatesForm
  components/sections/GraduatesFormSection.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/GraduatesFormData.ts
Labels: Feature

#893 Graduates form section
  components/sections/GraduatesFormSection.tsx
  utils/Renderers.tsx
  utils/strapi/queries.ts
  utils/strapi/sections/GraduatesFormData.ts
Labels: Feature
